---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name:
        - htop
        - tmux
  - name: copy wallpaper file
    copy:
      src: files/wallpaper.png
      dest: /usr/share/backgrounds/wallpaper.jpg
      owner: root
      group: root

  - name: set wallpaper
    become_user: itsmael
    dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file:///usr/share/backgrounnds/ansible-wallpaper.jpg'" 
  - name: set wallpaper position
    become_user: itsmael
    dconf:
      key: "/org/gnome/desktop/backgroun/pictures-options"
      value: "'zoom'"

